<template>
  <div class="spinner">
    <div class="loadingio-spinner-spinner-dbn0z9toih9">
      <div class="ldio-0u02u1ho1vjp">
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
      </div>
    </div>
    <div class="spinner__message">{{ message }}</div>
  </div>
</template>

<script>
export default {
  name: 'Spinner',
  props: {
    message: {
      type: String,
      default: '',
    },
  },
};
</script>

<style scoped>
@keyframes ldio-0u02u1ho1vjp {
  0% {
    opacity: 1;
  }
  100% {
    opacity: 0;
  }
}
.ldio-0u02u1ho1vjp div {
  left: 95px;
  top: 64px;
  position: absolute;
  animation: ldio-0u02u1ho1vjp linear 1s infinite;
  background: #85a2b6;
  width: 10px;
  height: 16px;
  border-radius: 5px / 8px;
  transform-origin: 5px 36px;
}
.ldio-0u02u1ho1vjp div:nth-child(1) {
  transform: rotate(0deg);
  animation-delay: -0.8888888888888888s;
  background: #85a2b6;
}
.ldio-0u02u1ho1vjp div:nth-child(2) {
  transform: rotate(40deg);
  animation-delay: -0.7777777777777778s;
  background: #85a2b6;
}
.ldio-0u02u1ho1vjp div:nth-child(3) {
  transform: rotate(80deg);
  animation-delay: -0.6666666666666666s;
  background: #85a2b6;
}
.ldio-0u02u1ho1vjp div:nth-child(4) {
  transform: rotate(120deg);
  animation-delay: -0.5555555555555556s;
  background: #85a2b6;
}
.ldio-0u02u1ho1vjp div:nth-child(5) {
  transform: rotate(160deg);
  animation-delay: -0.4444444444444444s;
  background: #85a2b6;
}
.ldio-0u02u1ho1vjp div:nth-child(6) {
  transform: rotate(200deg);
  animation-delay: -0.3333333333333333s;
  background: #85a2b6;
}
.ldio-0u02u1ho1vjp div:nth-child(7) {
  transform: rotate(240deg);
  animation-delay: -0.2222222222222222s;
  background: #85a2b6;
}
.ldio-0u02u1ho1vjp div:nth-child(8) {
  transform: rotate(280deg);
  animation-delay: -0.1111111111111111s;
  background: #85a2b6;
}
.ldio-0u02u1ho1vjp div:nth-child(9) {
  transform: rotate(320deg);
  animation-delay: 0s;
  background: #85a2b6;
}
.loadingio-spinner-spinner-dbn0z9toih9 {
  width: 200px;
  height: 200px;
  display: block;
  overflow: hidden;
  background: none;
  margin: auto;
}
.ldio-0u02u1ho1vjp {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-0u02u1ho1vjp div {
  box-sizing: content-box;
}
/* spinner is generated by https://loading.io/ */

.spinner {
  position: relative;
}

.spinner__message {
  text-align: center;
  position: absolute;
  bottom: 30px;
  left: 50%;
  transform: translateX(-50%);
}
</style>
